### ISSUE TITLE
Doesn't work on IE 9 and IE 10

### ISSUE THREAD

**Issue by chrouzz** [StreakYC/react-smooth-collapse#5]
I get an error message saying, impossible to get property 'collapse Height' of undefined or null reference

Is there any solution for that?

**Comment by chrouzz** [comment]
```
  (0, _createClass3.default)(SmoothCollapse, [{
    key: '_visibleWhenClosed',
    value: function _visibleWhenClosed(props) {
      if (!props) props = this.props;
      return parseFloat(props.collapsedHeight) !== 0;
    }
  },
```
this line is the issue, in IE 9 or 10 props is null or undefined
`return parseFloat(props.collapsedHeight) !== 0;`

**Comment by chrouzz** [comment]
I found the the issue is in IE9 and IE10 if I start my app with expanded=false on some element it will cause the issue.
and in IE9 the callback onChangeEnd doesn't fire

**Comment by Macil** [comment]
Does this error happen for you on the example page at https://streakyc.github.io/react-smooth-collapse/example/? For me, IE9 does not throw the error you said there, and it's not apparent to me how that error could happen. Can you link an example which gives an error? What version of React are you using?

I've fixed the issue where onChangeEnd did not fire in IE9. (There's now a fallback timer so it will fire after the amount of time the transition was set for if a transitionend event never happens.)

**Comment by alanbsmith** [comment]
I am also having this issue on IE 9-10. Thanks @chrouzz for pointing out the problematic line. I'm still not sure _why this issue is occurring._ However, I was able to resolve it by modifying
```
      if (!props) props = this.props;
```

to be: 
```
      if (!props) props = this.props || {};
```

Just a quick patch for now, but it seems to work as expected as far as I can tell.

**Comment by Macil** [comment]
Do you get this error in IE9 on https://streakyc.github.io/react-smooth-collapse/example/? If not, can you give an example of a page that does trigger the error?

**Comment by alanbsmith** [comment]
Thanks for your quick response (and apologies for my delay). We updated some of our internal dependencies and are no longer able reproduce the bug. Thanks again!

This issue is resolved for us.
